# Generated by Django 6.1 on 2026-08-19 06:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duel_date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('title', models.CharField(default='Daily Speed Arena', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DuelAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_handle', models.CharField(max_length=30)),
                ('correct_count', models.PositiveSmallIntegerField(default=0)),
                ('time_taken_seconds', models.FloatField(default=0.0)),
                ('final_score', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('duel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='duel.dailyduel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duel_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-final_score', 'time_taken_seconds'],
            },
        ),
        migrations.CreateModel(
            name='TriviaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TECH', 'Tech & Science'), ('POP', 'Pop Culture & Gaming'), ('HIST', 'World & History'), ('LOGIC', 'Puzzles & Logic')], default='TECH', max_length=10)),
                ('prompt', models.TextField()),
                ('option_a', models.CharField(max_length=200)),
                ('option_b', models.CharField(max_length=200)),
                ('option_c', models.CharField(max_length=200)),
                ('option_d', models.CharField(max_length=200)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('duel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='duel.dailyduel')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
