# Generated by Django 6.1 on 2026-08-19 07:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TECH', 'Tech & Science'), ('POP', 'Pop Culture & Gaming'), ('HIST', 'World & History'), ('LOGIC', 'Puzzles & Logic')], default='TECH', max_length=10)),
                ('prompt', models.TextField(unique=True)),
                ('option_a', models.CharField(max_length=200)),
                ('option_b', models.CharField(max_length=200)),
                ('option_c', models.CharField(max_length=200)),
                ('option_d', models.CharField(max_length=200)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='triviaquestion',
            name='duel',
        ),
        migrations.AddConstraint(
            model_name='duelattempt',
            constraint=models.UniqueConstraint(fields=('user', 'duel'), name='unique_user_daily_attempt'),
        ),
        migrations.AddField(
            model_name='dailyduel',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='duels', to='duel.questionbank'),
        ),
        migrations.DeleteModel(
            name='TriviaQuestion',
        ),
    ]
